# Generated by Django 5.0.4 on 2024-04-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appecommerce', '0006_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country_code',
            field=models.CharField(max_length=3),
        ),
    ]
