# Generated by Django 5.0.4 on 2024-04-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appecommerce', '0007_alter_address_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
