# Generated by Django 5.0.4 on 2024-04-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appecommerce', '0008_customuser_otp_customuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_wishlisted',
            field=models.BooleanField(default=False),
        ),
    ]
