# Generated by Django 5.0.4 on 2024-04-12 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appecommerce', '0010_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='stock_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='productbasic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appecommerce.productcategory'),
        ),
        migrations.AddField(
            model_name='productbasic',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appecommerce.widget'),
        ),
    ]
