# Generated by Django 5.0.4 on 2024-04-12 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appecommerce', '0011_inventory_stock_status_productbasic_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbasic',
            name='brand_name',
        ),
        migrations.AddField(
            model_name='productbasic',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='appecommerce.brand'),
        ),
    ]
