# Generated by Django 5.0.4 on 2024-04-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appecommerce', '0013_inventory_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
